const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
const ui={gold:document.getElementById('gold'),lives:document.getElementById('lives'),wave:document.getElementById('wave'),enemyCount:document.getElementById('enemyCount'),hint:document.getElementById('hint'),wavePreview:document.getElementById('wavePreview'),towerButtons:document.getElementById('towerButtons'),towerInfo:document.getElementById('towerInfo'),tiTitle:document.getElementById('tiTitle'),tiDesc:document.getElementById('tiDesc'),tiLevel:document.getElementById('tiLevel'),tiDamage:document.getElementById('tiDamage'),tiRange:document.getElementById('tiRange'),tiRole:document.getElementById('tiRole'),upgradeBtn:document.getElementById('upgradeBtn'),flameText:document.getElementById('flameText'),flameBar:document.getElementById('flameBar'),fireRain:document.getElementById('fireRain'),reinforce:document.getElementById('reinforce'),moveHeroBtn:document.getElementById('moveHeroBtn'),pauseBtn:document.getElementById('pauseBtn'),startWave:document.getElementById('startWave')};
let gold=420,lives=20,flame=0,wave=0,paused=false,waveActive=false,gameEnded=false,moveHeroMode=false,selectedTowerType='guard',selectedTower=null,towers=[],enemies=[],projectiles=[],allies=[],effects=[],queue=[],queueCd=0;
const path=[{x:-30,y:675},{x:220,y:675},{x:220,y:525},{x:520,y:525},{x:520,y:310},{x:825,y:310},{x:825,y:590},{x:1110,y:590},{x:1110,y:390},{x:1420,y:390},{x:1420,y:230},{x:1635,y:230}];
const pads=[{x:120,y:565},{x:360,y:620},{x:365,y:415},{x:655,y:425},{x:685,y:225},{x:950,y:435},{x:960,y:675},{x:1245,y:500},{x:1255,y:300},{x:1455,y:130}];
const towerDefs={guard:{name:'Стража',icon:'🛡️',cost:100,color:'#d7bb70',range:118,rate:1,damage:8,role:'Блокировка',desc:'Призывает солдат, которые удерживают врагов на дороге.'},ranger:{name:'Лесная башня',icon:'🏹',cost:115,color:'#58ce78',range:205,rate:.52,damage:16,role:'Дальний бой',desc:'Быстро обстреливает врагов с большого расстояния.'},forge:{name:'Руническая кузница',icon:'⚒️',cost:155,color:'#ff9d58',range:165,rate:1.45,damage:36,role:'Артиллерия',desc:'Медленный тяжёлый выстрел с уроном по области.'},crystal:{name:'Магическая башня',icon:'🔷',cost:145,color:'#6ed4ff',range:178,rate:.78,damage:22,role:'Магия',desc:'Магический урон и замедление; особенно сильна против теней.'}};
const enemyDefs={orc:{name:'Орк-мародёр',hp:95,speed:50,reward:14,armor:0,color:'#6c9848',r:16},scout:{name:'Разведчик',hp:58,speed:85,reward:12,armor:0,color:'#b8d766',r:13},ash:{name:'Тварь пепла',hp:82,speed:94,reward:16,armor:0,color:'#e25443',r:14},knight:{name:'Падший рыцарь',hp:235,speed:34,reward:28,armor:.45,color:'#596074',r:18},shadow:{name:'Тень',hp:132,speed:62,reward:24,armor:.65,magicWeak:true,color:'#7d68bb',r:15},boss:{name:'Вестник Пепла',hp:1550,speed:28,reward:220,armor:.25,color:'#91382c',r:31,boss:true}};
const waves=[['orc','orc','scout','orc','orc'],['orc','scout','scout','ash','orc','orc'],['orc','orc','ash','scout','scout','orc','orc'],['knight','orc','ash','orc','scout','knight'],['shadow','orc','ash','scout','shadow','orc','knight'],['knight','shadow','ash','ash','scout','shadow','orc'],['knight','shadow','ash','shadow','orc','orc','knight'],['orc','ash','shadow','knight','scout','ash','shadow','boss']];
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function nearestPathPoint(x,y){let best={x:path[0].x,y:path[0].y},bd=1e9;for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],vx=b.x-a.x,vy=b.y-a.y,l=vx*vx+vy*vy;let t=l?((x-a.x)*vx+(y-a.y)*vy)/l:0;t=Math.max(0,Math.min(1,t));const px=a.x+t*vx,py=a.y+t*vy,d=Math.hypot(x-px,y-py);if(d<bd){bd=d;best={x:px,y:py}}}return best}
function padAt(x,y){return pads.find(p=>Math.hypot(p.x-x,p.y-y)<34)}function towerAt(x,y){return towers.find(t=>Math.hypot(t.x-x,t.y-y)<34)}function findBlocker(e){let best=null,bd=999;for(const a of allies){if(!a.alive)continue;const m=a.type==='hero'?34:24,dd=dist(e,a);if(dd<m&&dd<bd){bd=dd;best=a}}return best}function say(t){ui.hint.innerHTML=t}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function drawShadow(x,y,rx,ry,a=.18){ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawEnemySprite(e){
 const x=e.x,y=e.y,s=e.boss?1.5:1;
 drawShadow(x,y+13*s,15*s,6*s,.2);
 ctx.save();ctx.translate(x,y);
 if(e.type==='shadow'){ctx.globalAlpha=.72;ctx.shadowBlur=20;ctx.shadowColor='#a18cff'}
 if(e.type==='ash'){ctx.shadowBlur=16;ctx.shadowColor='#ff6c38'}
 if(e.boss){ctx.shadowBlur=18;ctx.shadowColor='#ff654e'}
 if(e.type==='orc'||e.type==='scout'){ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(0,-8*s,7*s,0,Math.PI*2);ctx.fill();ctx.fillRect(-6*s,-2*s,12*s,15*s);ctx.fillStyle='#4b3425';ctx.fillRect(-8*s,4*s,16*s,5*s);ctx.strokeStyle='#3f2c20';ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(-4*s,12*s);ctx.lineTo(-8*s,22*s);ctx.moveTo(4*s,12*s);ctx.lineTo(8*s,22*s);ctx.stroke();ctx.strokeStyle='#75513c';ctx.beginPath();ctx.moveTo(5*s,1*s);ctx.lineTo(13*s,-9*s);ctx.stroke();if(e.type==='scout'){ctx.fillStyle='#d3c060';ctx.fillRect(-8*s,-5*s,16*s,3*s)}}
 if(e.type==='knight'){ctx.fillStyle='#454b59';ctx.fillRect(-8*s,-3*s,16*s,18*s);ctx.fillStyle='#6d7380';ctx.beginPath();ctx.arc(0,-10*s,8*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1f2430';ctx.fillRect(-6*s,-11*s,12*s,3*s);ctx.strokeStyle='#bcc2c8';ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(7*s,0);ctx.lineTo(14*s,12*s);ctx.stroke()}
 if(e.type==='ash'){ctx.fillStyle='#e3563f';ctx.beginPath();ctx.moveTo(0,-17*s);ctx.lineTo(10*s,-5*s);ctx.lineTo(6*s,14*s);ctx.lineTo(-7*s,14*s);ctx.lineTo(-11*s,-5*s);ctx.closePath();ctx.fill();ctx.fillStyle='#ffb14c';ctx.beginPath();ctx.arc(0,-4*s,4*s,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#7d261d';ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(-3*s,12*s);ctx.lineTo(-7*s,21*s);ctx.moveTo(3*s,12*s);ctx.lineTo(7*s,21*s);ctx.stroke()}
 if(e.type==='shadow'){ctx.fillStyle='#6d5ca7';ctx.beginPath();ctx.arc(0,-10*s,8*s,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-8*s,-5*s);ctx.lineTo(9*s,-5*s);ctx.lineTo(5*s,15*s);ctx.lineTo(0,9*s);ctx.lineTo(-5*s,15*s);ctx.closePath();ctx.fill();ctx.fillStyle='#b8a8ff';ctx.fillRect(-5*s,-11*s,3*s,2*s);ctx.fillRect(2*s,-11*s,3*s,2*s)}
 if(e.boss){ctx.fillStyle='#4d1613';ctx.fillRect(-12*s,-1*s,24*s,25*s);ctx.fillStyle='#9d3a2f';ctx.beginPath();ctx.arc(0,-14*s,11*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1b1113';ctx.beginPath();ctx.moveTo(-10*s,-19*s);ctx.lineTo(-4*s,-32*s);ctx.lineTo(0,-22*s);ctx.lineTo(5*s,-33*s);ctx.lineTo(11*s,-19*s);ctx.closePath();ctx.fill();ctx.strokeStyle='#ff8b54';ctx.lineWidth=3*s;ctx.beginPath();ctx.moveTo(-13*s,2*s);ctx.lineTo(-20*s,13*s);ctx.moveTo(13*s,2*s);ctx.lineTo(20*s,13*s);ctx.stroke()}
 ctx.restore();
}
function drawTowerSprite(t){
 const x=t.x,y=t.y,l=t.level;
 drawShadow(x,y+25,28,8,.18);ctx.save();ctx.translate(x,y);
 if(t.type==='guard'){ctx.fillStyle='#cbbf9d';ctx.fillRect(-18,-13,36,34);ctx.fillStyle='#8a7d66';ctx.fillRect(-21,16,42,8);ctx.fillStyle='#315f94';ctx.beginPath();ctx.moveTo(-23,-14);ctx.lineTo(0,-27-l*2);ctx.lineTo(23,-14);ctx.closePath();ctx.fill();ctx.fillStyle='#ece3c9';ctx.fillRect(-4,-3,8,13);ctx.fillStyle='#244c77';ctx.fillRect(16,-12,4,28);ctx.fillRect(20,-12,15,7)}
 if(t.type==='ranger'){ctx.fillStyle='#795536';ctx.fillRect(-13,-3,26,28);ctx.fillStyle='#b99b65';ctx.fillRect(-16,21,32,6);ctx.fillStyle='#5fb36c';ctx.beginPath();ctx.moveTo(0,-30-l*2);ctx.lineTo(24,-5);ctx.lineTo(-24,-5);ctx.closePath();ctx.fill();ctx.strokeStyle='#7f5f35';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-9,12,-1.3,1.3);ctx.stroke();ctx.beginPath();ctx.moveTo(7,-20);ctx.lineTo(17,-9);ctx.stroke()}
 if(t.type==='forge'){ctx.fillStyle='#655a4e';ctx.fillRect(-22,-2,44,29);ctx.fillStyle='#8b7663';ctx.fillRect(-25,22,50,7);ctx.fillStyle='#e78945';ctx.fillRect(-16,-18,32,17);ctx.fillStyle='#ffcf72';ctx.beginPath();ctx.arc(0,-8,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#49423a';ctx.fillRect(12,-28,9,22)}
 if(t.type==='crystal'){ctx.fillStyle='#385775';ctx.fillRect(-19,10,38,16);ctx.fillStyle='#28415b';ctx.fillRect(-13,-1,26,13);ctx.shadowBlur=20;ctx.shadowColor=t.color;ctx.fillStyle=t.color;ctx.beginPath();ctx.moveTo(0,-34-l*3);ctx.lineTo(15,-7);ctx.lineTo(7,13);ctx.lineTo(-7,13);ctx.lineTo(-15,-7);ctx.closePath();ctx.fill();ctx.shadowBlur=0}
 ctx.restore();ctx.fillStyle='#fff2bd';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText('ур. '+l,x,y+44);
}
function drawAllySprite(a){
 const x=a.x,y=a.y,hero=a.type==='hero';drawShadow(x,y+13,hero?14:9,5,.18);ctx.save();ctx.translate(x,y);
 if(hero){ctx.fillStyle='#2f5f96';ctx.beginPath();ctx.arc(0,-9,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3f73b3';ctx.fillRect(-6,-2,12,17);ctx.fillStyle='#d4b262';ctx.fillRect(-9,2,4,11);ctx.strokeStyle='#d9dbe0';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(6,1);ctx.lineTo(15,-9);ctx.stroke();ctx.fillStyle='#d6c6a1';ctx.beginPath();ctx.arc(0,-12,4,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#b9b28c';ctx.beginPath();ctx.arc(0,-6,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d2bd79';ctx.fillRect(-5,-1,10,13);ctx.fillStyle='#3f6088';ctx.fillRect(-9,0,4,11);ctx.strokeStyle='#b7bec7';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(5,1);ctx.lineTo(10,-6);ctx.stroke()}
 ctx.restore();const bw=hero?38:22;ctx.fillStyle='#102031';ctx.fillRect(x-bw/2,y-27,bw,4);ctx.fillStyle='#65d37b';ctx.fillRect(x-bw/2,y-27,bw*Math.max(0,a.hp/a.maxHp),4)
}
class Enemy{constructor(type){Object.assign(this,enemyDefs[type]);this.type=type;this.maxHp=this.hp;this.x=path[0].x;this.y=path[0].y;this.pathIndex=1;this.alive=true;this.attackCd=0;this.slow=0;this.summoned=false;this.pauseTime=0}update(dt){if(!this.alive)return;if(this.boss&&this.hp<this.maxHp*.65&&!this.summoned){this.summoned=true;this.pauseTime=2.4;spawnBossAdds(this);effects.push({type:'text',x:this.x,y:this.y-55,text:'ПРИЗЫВ!',life:1.2})}if(this.pauseTime>0){this.pauseTime-=dt;return}const blocker=findBlocker(this);if(blocker){this.attackCd-=dt;if(this.attackCd<=0){blocker.hp-=this.boss?36:(this.type==='knight'?18:10);this.attackCd=this.boss?1:1.05;effects.push({type:'slash',x:blocker.x,y:blocker.y,life:.18})}return}const target=path[this.pathIndex];if(!target){this.alive=false;lives--;if(lives<=0)endGame(false);return}if(this.slow>0)this.slow-=dt;const sp=this.speed*(this.slow>0?.55:1),dx=target.x-this.x,dy=target.y-this.y,d=Math.hypot(dx,dy);if(d<sp*dt){this.x=target.x;this.y=target.y;this.pathIndex++}else{this.x+=dx/d*sp*dt;this.y+=dy/d*sp*dt}}takeDamage(raw,kind='physical'){let dmg=raw;if(kind==='physical')dmg*=1-this.armor;if(kind==='magic'&&this.magicWeak)dmg*=1.65;this.hp-=dmg;if(this.hp<=0&&this.alive){this.alive=false;gold+=this.reward;flame=Math.min(100,flame+(this.boss?32:5));effects.push({type:'burst',x:this.x,y:this.y,life:.5})}}draw(){drawEnemySprite(this);const bw=this.boss?82:40;ctx.fillStyle='#102031';ctx.fillRect(this.x-bw/2,this.y-this.r-24,bw,5);ctx.fillStyle=this.boss?'#ff7653':'#69d781';ctx.fillRect(this.x-bw/2,this.y-this.r-24,bw*Math.max(0,this.hp/this.maxHp),5)}}
class Tower{constructor(x,y,type,pad){Object.assign(this,towerDefs[type]);this.type=type;this.x=x;this.y=y;this.pad=pad;this.level=1;this.cool=0;this.soldierCd=0;this.flash=0}update(dt){if(this.flash>0)this.flash-=dt;if(this.type==='guard')return this.updateGuard(dt);this.cool-=dt;let target=null,best=-1;for(const e of enemies){if(!e.alive)continue;const dd=dist(this,e);if(dd<=this.range&&e.pathIndex>=best){best=e.pathIndex;target=e}}if(target&&this.cool<=0){projectiles.push(new Projectile(this,target));this.cool=this.rate;this.flash=.12}}updateGuard(dt){this.soldierCd-=dt;const mine=allies.filter(a=>a.owner===this&&a.alive),limit=this.level>=3?3:2;if(mine.length<limit&&this.soldierCd<=0){const p=nearestPathPoint(this.x,this.y);allies.push(new Ally(p.x,p.y,this,'soldier'));this.soldierCd=2.6}}draw(){if(selectedTower===this){ctx.save();ctx.strokeStyle='rgba(255,225,150,.72)';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.beginPath();ctx.arc(this.x,this.y,this.range,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore()}drawTowerSprite(this);if(this.flash>0){ctx.save();ctx.globalAlpha=this.flash/.12;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(this.x,this.y,18,0,Math.PI*2);ctx.fill();ctx.restore()}}}
class Projectile{constructor(tower,target){this.tower=tower;this.target=target;this.x=tower.x;this.y=tower.y;this.alive=true;this.speed=tower.type==='forge'?280:540;this.damage=tower.damage*(1+(tower.level-1)*.45);this.kind=tower.type==='crystal'?'magic':'physical';this.color=tower.color}update(dt){if(!this.target||!this.target.alive){this.alive=false;return}const dx=this.target.x-this.x,dy=this.target.y-this.y,d=Math.hypot(dx,dy);if(d<10){if(this.tower.type==='forge'){for(const e of enemies)if(e.alive&&dist(e,this.target)<64)e.takeDamage(this.damage,'physical');effects.push({type:'blast',x:this.target.x,y:this.target.y,life:.25})}else{this.target.takeDamage(this.damage,this.kind);if(this.tower.type==='crystal')this.target.slow=1.4;effects.push({type:this.tower.type==='crystal'?'spark':'hit',x:this.target.x,y:this.target.y,life:.18})}this.alive=false;return}this.x+=dx/d*this.speed*dt;this.y+=dy/d*this.speed*dt}draw(){ctx.save();ctx.strokeStyle=this.color;ctx.lineWidth=this.tower.type==='crystal'?3:1.5;ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(this.x,this.y);ctx.lineTo(this.x-(this.target.x-this.x)*.05,this.y-(this.target.y-this.y)*.05);ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=this.color;if(this.tower.type==='ranger'){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(Math.atan2(this.target.y-this.y,this.target.x-this.x));ctx.fillRect(-7,-1,14,2);ctx.restore()}else{ctx.beginPath();ctx.arc(this.x,this.y,this.tower.type==='forge'?6:4,0,Math.PI*2);ctx.fill()}ctx.restore()}}
class Ally{constructor(x,y,owner,type='soldier'){this.x=x;this.y=y;this.owner=owner;this.type=type;this.maxHp=type==='hero'?320:85;this.hp=this.maxHp;this.alive=true;this.damage=type==='hero'?24:10;this.attackCd=0}update(dt){if(!this.alive)return;if(this.hp<=0){this.alive=false;if(this.type==='hero')setTimeout(()=>{if(!gameEnded){hero=new Ally(340,660,null,'hero');allies.push(hero);say('Арден вернулся в бой.')}},3500);return}let target=null,best=999;for(const e of enemies){if(!e.alive)continue;const dd=dist(this,e);if(dd<best&&dd<(this.type==='hero'?44:28)){best=dd;target=e}}this.attackCd-=dt;if(target&&this.attackCd<=0){target.takeDamage(this.damage,'physical');this.attackCd=this.type==='hero'?.62:.92;effects.push({type:'slash',x:target.x,y:target.y,life:.18})}}draw(){drawAllySprite(this)}}
let hero=new Ally(340,660,null,'hero');allies.push(hero);
function spawnBossAdds(b){for(let i=0;i<4;i++){const e=new Enemy(i<2?'orc':'ash');e.x=b.x-i*16;e.y=b.y+(i%2?18:-18);e.pathIndex=b.pathIndex;enemies.push(e)}say('Вестник Пепла остановился и призвал подкрепление!')}
function renderButtons(){ui.towerButtons.innerHTML='';Object.entries(towerDefs).forEach(([key,t])=>{const b=document.createElement('button');b.className='towerBtn'+(key===selectedTowerType?' active':'');b.innerHTML='<div class="ico">'+t.icon+'</div><b>'+t.name+'</b><small>'+t.cost+' золота</small>';b.onclick=()=>{selectedTowerType=key;selectedTower=null;hideInfo();renderButtons();say('Выбрана <b>'+t.name+'</b>. Поставьте её на светящуюся площадку.');};ui.towerButtons.appendChild(b)})}
function startWave(){if(waveActive||gameEnded||wave>=waves.length)return;wave++;waveActive=true;queue=[...waves[wave-1]];queueCd=.3;updatePreview();say('Волна <b>'+wave+'</b> началась.')}
function updatePreview(){const list=waves[Math.min(wave,waves.length-1)]||[];const c={};list.forEach(x=>c[x]=(c[x]||0)+1);ui.wavePreview.innerHTML=Object.entries(c).map(([k,n])=>'<div class="chip">'+enemyDefs[k].name+' × '+n+'</div>').join('')}
function showInfo(t){selectedTower=t;ui.towerInfo.classList.add('show');ui.tiTitle.textContent=t.name;ui.tiDesc.textContent=t.desc;ui.tiLevel.textContent=t.level;ui.tiDamage.textContent=Math.round(t.damage);ui.tiRange.textContent=Math.round(t.range);ui.tiRole.textContent=t.role;const cost=80+t.level*60;ui.upgradeBtn.disabled=t.level>=3;ui.upgradeBtn.textContent=t.level>=3?'Макс. уровень':'Улучшить · '+cost}
function hideInfo(){selectedTower=null;ui.towerInfo.classList.remove('show')}
function upgradeSelected(){if(!selectedTower)return;const cost=80+selectedTower.level*60;if(selectedTower.level>=3)return;if(gold<cost){say('Недостаточно золота.');return}gold-=cost;selectedTower.level++;selectedTower.damage*=1.22;selectedTower.range+=12;selectedTower.rate*=.93;showInfo(selectedTower)}
function updateUI(){ui.gold.textContent=Math.floor(gold);ui.lives.textContent=lives;ui.wave.textContent=wave+'/'+waves.length;ui.enemyCount.textContent=enemies.length+queue.length;ui.flameText.textContent=Math.floor(flame)+'/100';ui.flameBar.style.width=flame+'%';ui.fireRain.disabled=flame<60;ui.reinforce.disabled=flame<35;ui.fireRain.classList.toggle('ready',flame>=60);ui.reinforce.classList.toggle('ready',flame>=35)}
function endGame(win){if(gameEnded)return;gameEnded=true;say(win?'Победа! Лесной тракт удержан.':'Поражение. Тьма прорвалась к Храму Завета.');ui.startWave.disabled=true}
function update(dt){if(paused||gameEnded)return;if(waveActive&&queue.length){queueCd-=dt;if(queueCd<=0){enemies.push(new Enemy(queue.shift()));queueCd=.78}}enemies.forEach(e=>e.update(dt));towers.forEach(t=>t.update(dt));projectiles.forEach(p=>p.update(dt));allies.forEach(a=>a.update(dt));effects.forEach(f=>f.life-=dt);enemies=enemies.filter(e=>e.alive);projectiles=projectiles.filter(p=>p.alive);allies=allies.filter(a=>a.alive);effects=effects.filter(f=>f.life>0);if(waveActive&&!queue.length&&!enemies.length){waveActive=false;gold+=60+wave*8;flame=Math.min(100,flame+10);if(wave>=waves.length)endGame(true);else{say('Волна отбита. Подготовьте оборону.');updatePreview()}}updateUI()}
function cloud(x,y,s){ctx.beginPath();ctx.arc(x,y,s*.34,0,Math.PI*2);ctx.arc(x+s*.32,y+3,s*.28,0,Math.PI*2);ctx.arc(x-s*.3,y+7,s*.24,0,Math.PI*2);ctx.fill()}
function drawBG(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#9be0fb');g.addColorStop(.38,'#89cbb3');g.addColorStop(1,'#4f835f');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.55)';cloud(160,95,90);cloud(780,85,110);cloud(1260,125,75);ctx.fillStyle='#9bbdca';ctx.beginPath();ctx.moveTo(0,300);for(let x=0;x<=W;x+=140)ctx.lineTo(x,135+((x/140)%2?95:10));ctx.lineTo(W,340);ctx.lineTo(0,340);ctx.fill();const islands=[[170,175,150],[585,100,180],[1045,165,150],[1415,100,120]];islands.forEach(([x,y,r])=>{ctx.fillStyle='#5a7d4d';ctx.beginPath();ctx.ellipse(x,y,r,42,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6e604a';ctx.beginPath();ctx.moveTo(x-r*.66,y+20);ctx.lineTo(x,y+r*.92);ctx.lineTo(x+r*.66,y+20);ctx.closePath();ctx.fill();ctx.fillStyle='#d2c18a';for(let i=-2;i<=2;i++)ctx.fillRect(x+i*30-7,y-8,14,18)});ctx.fillStyle='rgba(214,248,255,.8)';ctx.fillRect(575,125,14,190);ctx.fillRect(1037,190,12,140);for(let i=0;i<85;i++){const x=(i*83)%W,y=365+((i*47)%410);ctx.fillStyle=i%3?'#2f7049':'#418457';ctx.beginPath();ctx.arc(x,y,11+(i%5)*2,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#2e4b69';ctx.fillRect(1515,155,52,120);ctx.fillStyle='#76dcff';ctx.beginPath();ctx.moveTo(1541,100);ctx.lineTo(1572,160);ctx.lineTo(1510,160);ctx.closePath();ctx.fill();ctx.fillStyle='#fff0b3';ctx.font='bold 15px Georgia';ctx.fillText('Храм Завета',1432,90);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#72573f';ctx.lineWidth=84;ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);for(let i=1;i<path.length;i++)ctx.lineTo(path[i].x,path[i].y);ctx.stroke();ctx.strokeStyle='#c8aa73';ctx.lineWidth=62;ctx.stroke();ctx.setLineDash([10,16]);ctx.strokeStyle='rgba(255,247,214,.52)';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([])}
function drawPads(){pads.forEach(p=>{const occupied=towers.some(t=>t.pad===p);ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=occupied?0:15;ctx.shadowColor='#ffe6a5';ctx.beginPath();ctx.arc(0,0,31,0,Math.PI*2);ctx.fillStyle=occupied?'rgba(41,67,91,.28)':'rgba(244,200,106,.18)';ctx.fill();ctx.strokeStyle=occupied?'rgba(255,255,255,.1)':'rgba(255,231,172,.8)';ctx.lineWidth=occupied?2:3;ctx.stroke();if(!occupied){ctx.beginPath();ctx.arc(0,0,14+Math.sin(performance.now()/230)*2.5,0,Math.PI*2);ctx.strokeStyle='rgba(255,243,203,.5)';ctx.stroke()}ctx.restore()})}
function drawEffects(){effects.forEach(f=>{ctx.save();ctx.globalAlpha=Math.min(1,f.life*5);if(f.type==='burst'){ctx.strokeStyle='#ffd76a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(f.x,f.y,42*(1-f.life),0,Math.PI*2);ctx.stroke()}if(f.type==='hit'){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(f.x,f.y,8,0,Math.PI*2);ctx.fill()}if(f.type==='spark'){ctx.strokeStyle='#8be3ff';ctx.lineWidth=3;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(f.x+Math.cos(i*1.57)*18,f.y+Math.sin(i*1.57)*18);ctx.stroke()}}if(f.type==='blast'){ctx.fillStyle='rgba(255,144,67,.5)';ctx.beginPath();ctx.arc(f.x,f.y,28,0,Math.PI*2);ctx.fill()}if(f.type==='slash'){ctx.strokeStyle='#fff3c5';ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,16,-.9,.9);ctx.stroke()}if(f.type==='text'){ctx.fillStyle='#ffd86d';ctx.font='bold 22px Georgia';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.restore()})}
function draw(){drawBG();drawPads();towers.forEach(t=>t.draw());allies.forEach(a=>a.draw());enemies.forEach(e=>e.draw());projectiles.forEach(p=>p.draw());drawEffects();if(paused){ctx.fillStyle='rgba(6,12,21,.48)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='bold 60px Georgia';ctx.textAlign='center';ctx.fillText('ПАУЗА',W/2,H/2)}}
canvas.addEventListener('click',e=>{if(gameEnded)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*(W/r.width),y=(e.clientY-r.top)*(H/r.height);const t=towerAt(x,y);if(t){showInfo(t);say('Выбрана '+t.name+'.');return}if(moveHeroMode){const p=nearestPathPoint(x,y);hero.x=p.x;hero.y=p.y;moveHeroMode=false;say('Арден перемещён.');return}const pad=padAt(x,y);if(!pad){hideInfo();say('Башни ставятся только на светящиеся площадки.');return}if(towers.some(t=>t.pad===pad)){say('Эта площадка уже занята.');return}const def=towerDefs[selectedTowerType];if(gold<def.cost){say('Недостаточно золота.');return}gold-=def.cost;const nt=new Tower(pad.x,pad.y,selectedTowerType,pad);towers.push(nt);showInfo(nt);say(def.name+' построена.');updateUI()});
ui.startWave.onclick=startWave;ui.pauseBtn.onclick=()=>{paused=!paused;ui.pauseBtn.textContent=paused?'Продолжить':'Пауза'};ui.moveHeroBtn.onclick=()=>{moveHeroMode=true;say('Кликните по дороге, куда должен перейти Арден.');};ui.upgradeBtn.onclick=upgradeSelected;
ui.fireRain.onclick=()=>{if(flame<60)return;flame-=60;enemies.forEach(e=>{if(e.alive)e.takeDamage(80,'magic')});effects.push({type:'text',x:W/2,y:120,text:'ОГНЕННЫЙ ДОЖДЬ',life:1.2});say('Огненный дождь обрушился на врагов!');updateUI()};
ui.reinforce.onclick=()=>{if(flame<35)return;flame-=35;const p=nearestPathPoint(hero.x+70,hero.y);for(let i=0;i<3;i++)allies.push(new Ally(p.x+i*14,p.y+16,null,'soldier'));say('Подкрепление прибыло.');updateUI()};
let last=performance.now();function loop(now){const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();requestAnimationFrame(loop)}
renderButtons();updatePreview();updateUI();requestAnimationFrame(loop);
